WINDOW_WIDTH = 500
WINDOW_HEIGHT = 250
FLAG_WIDTH = 3
FLAG_HEIGHT = 4
MINE_HEIGHT = 1
MINE_WIDTH = 3
BOARD_ROWS = 25
BOARD_SOLS = 50
SOLDIER_IMG = "soldier.png"
SOLDIER_BODY_HEIGHT = 4
SOLDIER_BODY_WIDTH = 2
SOLDIER_LEGS_HEIGHT = 1
SOLDIER_LEGS_WIDTH = 2


BACKGROUND_COLOR = (254, 252, 252)
GREEN = (138, 201, 38)
BLACK = (0, 0, 0)

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))


RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3